### ISSUE TITLE
Create Encryption pin text is off

### ISSUE THREAD

**Issue by Woofer21** [Satellite-im/Satellite#13]
the UI and the text is off see screens hot below the latest build
![image](https://user-images.githubusercontent.com/61364477/102703805-9bda1400-4241-11eb-998a-9df2982d1439.png)

**Comment by Jaden-Giordano** [comment]
@RetroPronghorn I know you said you were gonna work on this but you could actually just assign this issue to me and I'll start deveelopment on the new mock ups I did.

**Comment by Jaden-Giordano** [comment]
Here is a preview of the new lock screen design:
![locked](https://user-images.githubusercontent.com/5057468/110884765-771e9700-829a-11eb-9a59-951a01b96203.png)

Im also going to link the prototype and the design below:
https://www.figma.com/file/onEZiLtbxGN9hqq3rUWTIq/satellite.im-lock-screen?node-id=0%3A1

https://www.figma.com/proto/onEZiLtbxGN9hqq3rUWTIq/satellite.im-lock-screen?node-id=1%3A2&viewport=457%2C443%2C0.4858739674091339&scaling=min-zoom
